-- ============================================================
-- Part 18 실습 04: CPU 사용률 (V$OSSTAT)
-- CPU사용률 = BUSY_TIME / (BUSY_TIME + IDLE_TIME) * 100
-- ============================================================
SET LINESIZE 200 PAGESIZE 100

PROMPT ========================================
PROMPT 1. 현재 CPU 사용률 (누적 기준)
PROMPT ========================================
SELECT ROUND(
  (SELECT VALUE FROM V$OSSTAT WHERE STAT_NAME = 'BUSY_TIME')
  / NULLIF(
    (SELECT VALUE FROM V$OSSTAT WHERE STAT_NAME = 'BUSY_TIME')
    + (SELECT VALUE FROM V$OSSTAT WHERE STAT_NAME = 'IDLE_TIME'), 0)
  * 100, 2) AS "CPU Usage %"
FROM DUAL;

PROMPT ========================================
PROMPT 2. CPU 상세 통계
PROMPT    USER_TIME > SYS_TIME이 정상
PROMPT    SYS_TIME 지속 증가 = OS Level 점검 필요
PROMPT ========================================
SELECT STAT_NAME, VALUE,
       ROUND(VALUE / 100, 2) AS SECONDS
  FROM V$OSSTAT
 WHERE STAT_NAME IN ('NUM_CPUS','BUSY_TIME','IDLE_TIME','USER_TIME','SYS_TIME','IOWAIT_TIME')
 ORDER BY DECODE(STAT_NAME, 'NUM_CPUS',1, 'BUSY_TIME',2, 'IDLE_TIME',3, 'USER_TIME',4, 'SYS_TIME',5, 6);

PROMPT ========================================
PROMPT 3. AWR CPU Trend (최근 3시간)
PROMPT    CPU% 급등 구간 찾기
PROMPT ========================================
SELECT S.SNAP_ID,
       TO_CHAR(S.END_INTERVAL_TIME, 'HH24:MI') AS SNAP_TIME,
       ROUND((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID))
           / NULLIF((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID))
                  + (O_IDLE.VALUE - LAG(O_IDLE.VALUE) OVER(ORDER BY S.SNAP_ID)), 0)
           * 100, 2) AS CPU_PCT,
       ROUND((O_USER.VALUE - LAG(O_USER.VALUE) OVER(ORDER BY S.SNAP_ID))
           / NULLIF((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID)), 0)
           * 100, 2) AS USER_PCT,
       ROUND((O_SYS.VALUE - LAG(O_SYS.VALUE) OVER(ORDER BY S.SNAP_ID))
           / NULLIF((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID)), 0)
           * 100, 2) AS SYS_PCT
  FROM DBA_HIST_SNAPSHOT S
  JOIN DBA_HIST_OSSTAT O_BUSY ON S.SNAP_ID = O_BUSY.SNAP_ID AND S.DBID = O_BUSY.DBID
       AND S.INSTANCE_NUMBER = O_BUSY.INSTANCE_NUMBER AND O_BUSY.STAT_NAME = 'BUSY_TIME'
  JOIN DBA_HIST_OSSTAT O_IDLE ON S.SNAP_ID = O_IDLE.SNAP_ID AND S.DBID = O_IDLE.DBID
       AND S.INSTANCE_NUMBER = O_IDLE.INSTANCE_NUMBER AND O_IDLE.STAT_NAME = 'IDLE_TIME'
  JOIN DBA_HIST_OSSTAT O_USER ON S.SNAP_ID = O_USER.SNAP_ID AND S.DBID = O_USER.DBID
       AND S.INSTANCE_NUMBER = O_USER.INSTANCE_NUMBER AND O_USER.STAT_NAME = 'USER_TIME'
  JOIN DBA_HIST_OSSTAT O_SYS ON S.SNAP_ID = O_SYS.SNAP_ID AND S.DBID = O_SYS.DBID
       AND S.INSTANCE_NUMBER = O_SYS.INSTANCE_NUMBER AND O_SYS.STAT_NAME = 'SYS_TIME'
 WHERE S.END_INTERVAL_TIME > SYSDATE - 3/24
   AND S.INSTANCE_NUMBER = (SELECT INSTANCE_NUMBER FROM V$INSTANCE)
 ORDER BY S.SNAP_ID;
