-- ============================================================
-- Part 18 실습 05: TOP SQL 분석 (V$SQL + DBA_HIST_SQLSTAT)
-- ============================================================
SET LINESIZE 200 PAGESIZE 100

PROMPT ========================================
PROMPT 1. Top 10 SQL by Elapsed Time (현재 메모리)
PROMPT ========================================
COL SQL_TEXT FOR A55
SELECT SQL_ID, PLAN_HASH_VALUE,
       EXECUTIONS AS EXEC,
       ROUND(ELAPSED_TIME / 1000000, 2) AS ELAPSED_SEC,
       ROUND(CPU_TIME / 1000000, 2) AS CPU_SEC,
       BUFFER_GETS AS GETS,
       DISK_READS AS READS,
       ROUND(BUFFER_GETS / NULLIF(EXECUTIONS, 0)) AS GETS_PER_EXEC,
       SUBSTR(SQL_TEXT, 1, 55) AS SQL_TEXT
  FROM V$SQL
 WHERE EXECUTIONS > 0
   AND PARSING_SCHEMA_NAME NOT IN ('SYS','SYSTEM','DBSNMP','SYSMAN')
 ORDER BY ELAPSED_TIME DESC
 FETCH FIRST 10 ROWS ONLY;

PROMPT ========================================
PROMPT 2. Top 10 SQL by Buffer Gets (논리적 I/O)
PROMPT    GETS_PER_EXEC가 높으면 튜닝 대상
PROMPT ========================================
SELECT SQL_ID, PLAN_HASH_VALUE,
       EXECUTIONS AS EXEC,
       BUFFER_GETS AS GETS,
       ROUND(BUFFER_GETS / NULLIF(EXECUTIONS, 0)) AS GETS_PER_EXEC,
       DISK_READS AS READS,
       ROUND(ELAPSED_TIME / 1000000, 2) AS ELAPSED_SEC,
       SUBSTR(SQL_TEXT, 1, 55) AS SQL_TEXT
  FROM V$SQL
 WHERE EXECUTIONS > 0
   AND PARSING_SCHEMA_NAME NOT IN ('SYS','SYSTEM','DBSNMP','SYSMAN')
 ORDER BY BUFFER_GETS DESC
 FETCH FIRST 10 ROWS ONLY;

PROMPT ========================================
PROMPT 3. AWR Top SQL (최근 스냅샷 구간)
PROMPT ========================================
SELECT SQL_ID, PARSING_SCHEMA_NAME AS SCHEMA,
       SUM(EXECUTIONS_DELTA) AS EXEC_CNT,
       ROUND(SUM(ELAPSED_TIME_DELTA) / 1000000, 2) AS ELAPSED_SEC,
       ROUND(SUM(CPU_TIME_DELTA) / 1000000, 2) AS CPU_SEC,
       SUM(BUFFER_GETS_DELTA) AS BUFFER_GETS,
       SUM(DISK_READS_DELTA) AS DISK_READS,
       ROUND(SUM(BUFFER_GETS_DELTA) / NULLIF(SUM(EXECUTIONS_DELTA), 0)) AS GETS_PER_EXEC
  FROM DBA_HIST_SQLSTAT
 WHERE SNAP_ID BETWEEN (SELECT MAX(SNAP_ID)-2 FROM DBA_HIST_SNAPSHOT WHERE INSTANCE_NUMBER=1)
                    AND (SELECT MAX(SNAP_ID) FROM DBA_HIST_SNAPSHOT WHERE INSTANCE_NUMBER=1)
   AND DBID = (SELECT DBID FROM V$DATABASE)
   AND INSTANCE_NUMBER = (SELECT INSTANCE_NUMBER FROM V$INSTANCE)
   AND PARSING_SCHEMA_NAME NOT IN ('SYS','SYSTEM','DBSNMP','SYSMAN')
 GROUP BY SQL_ID, PARSING_SCHEMA_NAME
HAVING SUM(EXECUTIONS_DELTA) > 0
 ORDER BY ELAPSED_SEC DESC
 FETCH FIRST 15 ROWS ONLY;
