-- ============================================================
-- Part 18 실습 08: 통합 성능 Trend (실무 분석 프로세스)
-- ① CPU → ② DB_TIME → ③ WAIT EVENT → ④ TOP SQL → ⑤ ASH
-- ============================================================
SET LINESIZE 200 PAGESIZE 100

PROMPT ========================================
PROMPT [종합 대시보드] 최근 3시간 10분 단위 Trend
PROMPT CPU% | DB_TIME | Logical I/O | Physical I/O | Redo
PROMPT ========================================
SELECT S.SNAP_ID,
       TO_CHAR(S.END_INTERVAL_TIME, 'HH24:MI') AS SNAP_TIME,
       -- CPU %
       ROUND((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID))
           / NULLIF((O_BUSY.VALUE - LAG(O_BUSY.VALUE) OVER(ORDER BY S.SNAP_ID))
                  + (O_IDLE.VALUE - LAG(O_IDLE.VALUE) OVER(ORDER BY S.SNAP_ID)), 0)
           * 100, 1) AS "CPU%",
       -- DB_TIME (초)
       ROUND((T.VALUE - LAG(T.VALUE) OVER(ORDER BY S.SNAP_ID)) / 1000000, 1) AS "DB_TIME(s)",
       -- Session Logical Reads
       ROUND((SS_LR.VALUE - LAG(SS_LR.VALUE) OVER(ORDER BY S.SNAP_ID)) / 1000, 1) AS "LogicalIO(K)",
       -- Physical Reads
       ROUND((SS_PR.VALUE - LAG(SS_PR.VALUE) OVER(ORDER BY S.SNAP_ID)) / 1000, 1) AS "PhysIO(K)",
       -- Redo (MB)
       ROUND((SS_RD.VALUE - LAG(SS_RD.VALUE) OVER(ORDER BY S.SNAP_ID)) / 1024/1024, 1) AS "Redo(MB)",
       -- Execute Count
       (SS_EX.VALUE - LAG(SS_EX.VALUE) OVER(ORDER BY S.SNAP_ID)) AS "Executes"
  FROM DBA_HIST_SNAPSHOT S
  -- CPU
  JOIN DBA_HIST_OSSTAT O_BUSY ON S.SNAP_ID=O_BUSY.SNAP_ID AND S.DBID=O_BUSY.DBID
       AND S.INSTANCE_NUMBER=O_BUSY.INSTANCE_NUMBER AND O_BUSY.STAT_NAME='BUSY_TIME'
  JOIN DBA_HIST_OSSTAT O_IDLE ON S.SNAP_ID=O_IDLE.SNAP_ID AND S.DBID=O_IDLE.DBID
       AND S.INSTANCE_NUMBER=O_IDLE.INSTANCE_NUMBER AND O_IDLE.STAT_NAME='IDLE_TIME'
  -- DB_TIME
  JOIN DBA_HIST_SYS_TIME_MODEL T ON S.SNAP_ID=T.SNAP_ID AND S.DBID=T.DBID
       AND S.INSTANCE_NUMBER=T.INSTANCE_NUMBER AND T.STAT_NAME='DB time'
  -- SYSSTAT
  JOIN DBA_HIST_SYSSTAT SS_LR ON S.SNAP_ID=SS_LR.SNAP_ID AND S.DBID=SS_LR.DBID
       AND S.INSTANCE_NUMBER=SS_LR.INSTANCE_NUMBER AND SS_LR.STAT_NAME='session logical reads'
  JOIN DBA_HIST_SYSSTAT SS_PR ON S.SNAP_ID=SS_PR.SNAP_ID AND S.DBID=SS_PR.DBID
       AND S.INSTANCE_NUMBER=SS_PR.INSTANCE_NUMBER AND SS_PR.STAT_NAME='physical reads'
  JOIN DBA_HIST_SYSSTAT SS_RD ON S.SNAP_ID=SS_RD.SNAP_ID AND S.DBID=SS_RD.DBID
       AND S.INSTANCE_NUMBER=SS_RD.INSTANCE_NUMBER AND SS_RD.STAT_NAME='redo size'
  JOIN DBA_HIST_SYSSTAT SS_EX ON S.SNAP_ID=SS_EX.SNAP_ID AND S.DBID=SS_EX.DBID
       AND S.INSTANCE_NUMBER=SS_EX.INSTANCE_NUMBER AND SS_EX.STAT_NAME='execute count'
 WHERE S.END_INTERVAL_TIME > SYSDATE - 3/24
   AND S.INSTANCE_NUMBER = (SELECT INSTANCE_NUMBER FROM V$INSTANCE)
 ORDER BY S.SNAP_ID;

PROMPT ========================================
PROMPT [실무 분석 프로세스]
PROMPT ① 위 Trend에서 CPU%/DB_TIME 급증 구간 식별
PROMPT ② 해당 구간 WAIT EVENT 분석 (03_wait_event.sql)
PROMPT ③ TOP SQL 확인 (05_top_sql.sql)
PROMPT ④ ASH로 상세 분석 (06_ash.sql)
PROMPT ⑤ SQL 튜닝 또는 인프라 조치
PROMPT ========================================
